### ISSUE TITLE
Kubernetes version different to that in Linux Founddation

### ISSUE THREAD

**Issue by vikas027** [cncf/curriculum#28]
Kubernetes version in the repository is v.1.13.0 but on Linux Foundation [site](https://training.linuxfoundation.org/certification/certified-kubernetes-application-developer-ckad/) it is v1.14

Which one shall I deploy for preparation? :)

**Comment by staranto** [comment]
Exams are updated to 1.14.

**Comment by kbarnard10** [comment]
The curriculum version has also been updated to reflect this.
