### ISSUE TITLE
CKA Curriculum for 1.15

### ISSUE THREAD

**Issue by bimalvasan** [cncf/curriculum#31]
The linux foundation site shows version as **Kubernetes v1.15** - https://training.linuxfoundation.org/certification/certified-kubernetes-administrator-cka/#overview
But curriculum pdf is not updated.

**Comment by alanjcastonguay** [comment]
Curriculum PDF updated in commit 3aa63787

**Comment by leandrocostam** [comment]
@bimalvasan  There is a new 1.17 version available.  Can we close this issue?

**Comment by bimalvasan** [comment]
Closing. Thanks
