### ISSUE TITLE
Clarification on CKA v1.15 Ciurriculum

### ISSUE THREAD

**Issue by David-VTUK** [cncf/curriculum#33]
Compared to v1.14.1 the only difference I can see is the following being **omitted** from v1.15.

•Install and use kubeadm to install,configure, and manage Kubernetes clusters.
(new kubeadm competency coming in 1.15)

Has this requirement been withdrawn? There doesn't seem to be any mention of kubeadm in the 1.15 curriculum.

Thanks,

**Comment by alanjcastonguay** [comment]
3aa63787

**Comment by gtseres** [comment]
@alanjcastonguay given that there is already a curriculum available for 1.15, maybe this issue can be closed.

**Comment by alanjcastonguay** [comment]
No objection, though I have no close button. Someone from the CNCF (or David) could close it.
