### ISSUE TITLE
CKA Curriculum for 1.16

### ISSUE THREAD

**Issue by gtseres** [cncf/curriculum#36]
The [CKA handbook](https://training.linuxfoundation.org/wp-content/uploads/2019/11/CKA-CKAD-Candidate-Handbook-v1.6.pdf) has been updated to use Kubernetes version 1.16. It would be great if the corresponding curriculum would be available.

**Comment by sheijmans** [comment]
<bump>

**Comment by alex-leonhardt** [comment]
When will this be made available?

**Comment by leandrocostam** [comment]
@gtseres there is a new 1.17 version available.  Can we close this issue?

**Comment by gtseres** [comment]
Hello @leandrocostam. Thanks a lot! Sure, closing the issue.
