### ISSUE TITLE
Request for New certificate CKSS for security 

### ISSUE THREAD

**Issue by abdennour** [cncf/curriculum#39]
I've achieved CKA and CKAD since 2018.
Since that time, I've ran Kubernetes clusters on production.

I found that the security part is very critical while it's not covered deeply neither on CKA nor CKAD.

I would like to suggest a 3rd certification curriculum named: 
- **CKSS** or **Certified Kubernetes  Security Specialist**

I would suggest the following topics for this certificate: 
- CNI plugins
- NetworkPolicies : Ingress, Egress, so on.
- Data encryption at rest (PV/PVC) or in transit (TLS, .. so on).
- Network Performance

**Comment by medkbadri** [comment]
Absolutely agree!

**Comment by walidshaari** [comment]
it is a must for the enterprise, how about an architect first as CKA covers security and it is around 12% of the exam, while CKAD does not, however, covers a bit of networking less than 6%., an Architect might cover more security topics

**Comment by mrudrara** [comment]
I agree 100% Certified Kubernetes Security Specialist is must have

**Comment by ijelliti** [comment]
CKSS can be more on network overlays in k8s, how network policies are implemented(calico), building & maintain a secure kubernetes infrastructure , also on monitoring and alerts,...

**Comment by sftim** [comment]
It seems tricky to strike a balance between:
- asking questions about CNI, Ingress (the resource), per-Pod `sysctl` settings etc
- those features not yet being GA; CNI is actually still alpha

I'd like to see a few more security-related questions as part of CKA and especially CKAD.
Understanding how Secret does (and doesn't) protect credentials is important. Also things like [client-go credential plugins](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins) (also beta)

If it's hard to evaluate people's skills in these areas, does that help make a stronger case for taking those components forward to a stable, GA status? I don't know if there's some part of Kubernetes / CNCF governance that can take that into account.

@abdennour - I see that 3 of the 4 topics you mentioned relate to networking. If there were a certificate related to cloud-native / Kubernetes networking, with security making up a good chunk of the curriculum, how well would that match up to what you wanted?

**Comment by jonpulsifer** [comment]
This was fixed in https://github.com/cncf/curriculum/commit/0f652d0dc809d6cca6c8e6afa1134a1612baf2e3 and is currently available here: https://github.com/cncf/curriculum/blob/master/CKS_Curriculum_%20v1.19.pdf
