### ISSUE TITLE
Typo in the CKAD_Curriculum_V1.17.pdf

### ISSUE THREAD

**Issue by PavanYadala** [cncf/curriculum#41]
Hi there,

The POD design has bee mentioned twice in the curriculum. Please get this corrected to State Persistence. 

<img width="623" alt="CKAD" src="https://user-images.githubusercontent.com/36486784/74139465-b4c27380-4bf3-11ea-84f9-374407ffdfd6.PNG">

**Comment by lizkline** [comment]
Thanks for pointing out the typo in the CKAD curriculum. It has been fixed.
