### ISSUE TITLE
Unable to use kubectl commands

### ISSUE THREAD

**Issue by krishna13052001** [cncf/curriculum#58]
![Uploading Screenshot 2022-04-09 at 10.10.47 PM.png…]()

While running the kubectl command receiving the error unable to connect to the server.

I any know knows how to resolve the issue please help me.

**Comment by Tej-Singh-Rana** [comment]
Hi,
This is not the right place to discuss these issues.
Please create a new post on the community site.

https://discuss.kubernetes.io/ 

Regards,
