### ISSUE TITLE
Link Broken: https://www.cncf.io/certification/expert/faq

### ISSUE THREAD

**Issue by s4rd1nh4** [cncf/curriculum#6]
Link Broken: https://www.cncf.io/certification/expert/faq

**Comment by dankohn** [comment]
Thanks for noticing. @taylorwaggoner or @kbarnard10  please fix the link under the certification menu. I believe Expert Certification should not link to anything, rather than linking to the FAQ.

**Comment by kbarnard10** [comment]
@s4rd1nh4 @dankohn Updated - thanks!
