### ISSUE TITLE
Couldn't open "CKAD_Curriculum_v1.23.pdf"

### ISSUE THREAD

**Issue by Darshan174** [cncf/curriculum#61]
when clicked in this file, it shows "[CKAD_Curriculum_v1.23.pdf]"
![gitHuberrorss](https://user-images.githubusercontent.com/91359578/178977552-767ab092-9865-40a1-9d4a-2fa2f88c195a.png)

**Comment by Tej-Singh-Rana** [comment]
It's opening for me. Why don't you try to download the file?
