### ISSUE TITLE
What are the Primitives?

### ISSUE THREAD

**Issue by shadycuz** [cncf/curriculum#8]
Primitives are listed under both CKAD and CKA. Yet I nor my colleagues can find any official documentation on what those primitives are. 

Are we talking about Pods, Labels & Selectors, Controllers and Services like Wikipedia states? Or are we talking things like deployments, secrets, configmaps and stateful sets for the CKAD and other objects for the CKA?

I would like the curriculum to better state what these items will be for each Certification. 

Edit: Found this in the latest [Kubernetes.io blog post](https://kubernetes.io/blog/).

> Persistent storage is important for running stateful applications, and Kubernetes has supported these workloads with StatefulSets, PersistentVolumeClaims and PersistentVolumes. These primitives have supported remote volume types well, where the volumes can be accessed from any node in the cluster, but did not support local volumes, where the volumes can only be accessed from a specific node.

I feel an exact list of the primitives covered in each exam would give me more confidence in my studying.

**Comment by grastogi78** [comment]
Thanks shadycuz for raising this request! this is a big chunk in the exam and we would really appreciate any clarification. Thanking the team in advance!

**Comment by nicoclau** [comment]
Unless I am mistaken, primitives here would be basic commands in kubectl for working with workloads.

**Comment by shadycuz** [comment]
Well, I did get my CKAD and to be honest, still don't know what exactly it means by primitives. 

@nicoclau when you say basic commands you identify them?  I'm guessing we are talking about "everything" which will be a scary exam by the time I need to renew my cert. 

I haven't looked so maybe the primitives are documented now. The issue didn't really get any attention is 2 years so I will just close it.
